INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Mr White',7,'Meses',1,'https://i.postimg.cc/wTQrs1cZ/1.jpg','Gato macho, encontrado a la veda de calle. Esta castrado, es vilef Positivo. Es una bola blanca, muy miedoso y mimoso. Le gusta jugar. Necesita una familia que no tenga otros gatos o que tenga gatos con vilef positivo. Vive encerrado en una habitacion, tengo 5 gatos y no pueden convivir. Necesito urgente transito o casa adoptiva para el gato. ','@diegocoppa',1);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Franquito',2,'Anios',1,'https://i.postimg.cc/fRHgB1Pv/2.jpg','Muy carinioso.','@casamiau.ar',2);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Magdalena',3,'Anios',2,'https://i.postimg.cc/rpKZbQX2/3.jpg','Le da miedo los ruidos fuertes.','@casamiau.ar',2);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Lucia',2,'Anios',2,'https://i.postimg.cc/9fKgjZCR/4.jpg','-','@casamiau.ar',2);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Garcia',4,'Anios',1,'https://i.postimg.cc/HnCSrmJT/5.jpg','Garcia es un personaje unico.Se puede llevar a domicilio','@casamiau.ar',2);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Limona',9,'Meses',2,'https://i.postimg.cc/BbcmDzDH/6.jpg','Limona es una gatita super dulce y es ideal para ser gatita unica por ser vilef + (o vivir con otros gatis vilef +)','@casamiau.ar',2);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Kila',2,'Anios',2,'https://i.postimg.cc/dQ8HzhX3/7.jpg','Kila es una gatita super tranquila, le gusta estar en su mundo o con sus hijitos que los ama.Ya esta castrada y se puede llevar a domicilio','@casamiau.ar',2);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Limon',7,'Meses',1,'https://i.postimg.cc/Wb891QsP/8.jpg','Simplemente maravilloso. Es hermosamente carinioso y jugueton pero a la vez guardian.Es tan mimoso que te sigue a todos lados, le encanta salir a pasear y jugar con pelotas y sogas. Si te agachas se sube a tu espalda y lo podes llevar a "cocochito".Esta desparasitado y vacunado.','@evelynlynlynn',3);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Caramelo',7,'Meses',1,'https://i.postimg.cc/QdMf90MK/9.jpg','Perro tricolor, mas hermoso de lo que se puede apreciar en la foto. Es muy mimoso y carinioso aunque puede ser travieso. Le gustan los paseos en la plaza y jugar con pelotas y sogas.Esta desparasitado y vacunado.','@evelynlynlynn',3);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Zeus',5,'Anios',1,'https://i.postimg.cc/zGP0nKLt/10.jpg','Pitbull puro, belleza total, protector, amoroso y muy mimoso, se encuentra vacunado y castrado.','@blanqueriaelamanecer',4);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Gala',5,'Anios',2,'https://i.postimg.cc/d0knn3rq/11.jpg','Galita es una guerrera, vivio en la calle, no sabemos cuanto, pero paso muchas necesidades, hasta la vi esconder un vomito "para comerlo despues"... tuvo cria muchas veces pero por suerte esta vez fue la ultima. Es tranquila, companiera, ama salir a pasear, es extremadamente mimosa, es tamanio mediana tipo pitbull y super super docil. Cuantas veces habra parido y sufrido para sobrevivir.','@maimessina',5);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Rubi',5,'Anios',2,'https://i.postimg.cc/5thgrJS8/12.jpg','Se entrega castrada, desparasitada y con pipeta al dia ! Fue encontrada vagando en el tren con toda su cabeza lastimada, dejandose morir, por suerte llegamos a tiempo. Hace mucho tiempo esta en el transito y espera una familia que la ame y cuide para siempre, eso que no conocio de chiquita.','@maimessina',5);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Sunshine',1,'Anios',1,'https://i.postimg.cc/0Q7nR4VF/13.jpg','Es amoroso, amable e independiente.Utiliza su arenero si no no realiza sus necesidades , no rasca muebles etc juega con su rascador y puente colgante .No larga pelo , es territorial con otros animales, no es apto para convivir con otras mascotas ya que es un gato macho alfa dominante con el resto de la manada e inicia peleas .','@Yobruja2024',6);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Indio',1,'Anios',1,'https://i.postimg.cc/tRtkBLZV/14.jpg','Ya esta castrado, le encanta jugar y dormir siesta, le gusta los mimos y que le rasquen la panza.','@Aguus_gimenez__',6);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Cloe',4,'Anios',2,'https://i.postimg.cc/zXxjrKkz/15.jpg','Su humana fallecio y la dejaron en la calle.Se encuentra castrada con todas las vacunas al dia. Es muy amorosa y ama estar en companiia.','@Caroazerrat',7);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Dorothea',5,'Meses',2,'https://i.postimg.cc/T1G9RcSw/16.jpg','Es una gatita super super mimosa, le gusta jugar muchisimo y requiere mucho tiempo porque le gusta mucho estar con uno. Esta desparasitada y despulgada','@hogardegatitos1',8);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Severino',4,'Anios',1,'https://i.postimg.cc/vHxz73Ts/17.jpg','Severino es un gato super carinioso y companiero. Esta castrado y tiene las vacunas al dia, usa su arenero, es muy jugueton y le gusta mucho estar con sus humanos. Vivimos juntos hace 3 anios pero estoy por irme a vivir afuera del pais y no puedo llevarlo conmigo. Buscamos a alguien que pueda darle muchisimo amor y quiera compartir la vida con un gatito muy especial.','@joacomuino',9);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Tom',1,'Anios',1,'https://i.postimg.cc/wB2cxrfh/18.jpg','Perro tamanio mediano. Rescatado en una ruta de Jujuy, lo trajimos vacunado con antipulgas y garraparas a Bs. As. Ya vacunado y castrado. Excelente relacion con ninios, otros perros y gatos.','@Carito.h1',10);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Coca',45,'Dias',2,'https://i.postimg.cc/FHtxT3kJ/19.jpg','Hola! Soy coca. Me pusieron asi por la coca cola, estoy en transito y busco una familia responsable que me adopte y me de mucho carinio. La adopcion es con seguimiento y compromiso de castracion. Soy muy mimosa y buenita me llevo bien con otros gatos pero con perros no.','@p_sepulveeda',11);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Lola',6,'Anios',2,'https://i.postimg.cc/x1K3h8Lp/20.jpg','Perrita super amorosa, docil, cariniosa y tranquila. Tamanio intermedio. Castrada, vacunada, desparasitada y con pipeta al dia.','@camidecundo',12);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Flora',55,'Dias',2,'https://i.postimg.cc/MGqmSwD6/21.jpg','Llego con muchos parasitos, flaquita y con pulgas. Con mucho carinio y paciencia subio de peso y su humor cambio. Aprendio a convivir con otros gatos y perros en cuestion de horas. Sabe usar las piedritas. Se entrega desparasitada y despulgada!!','@lo.velazquezz',13);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Tigri',2,'Meses',2,'https://i.postimg.cc/05FGNDfH/22.jpg','Hola! Soy Tigri, tengo 2 meses y tengo muchas ganas de poder formar parte de una familia definitiva donde me cuiden y me mimen. Me rescataron cuando tenia solo un mes y creci muy sana desde entonces.','@salooescobar',14);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Luca',1,'Anios',1,'https://i.postimg.cc/nryqwfrt/23.jpg','Se busca adopcion responsable para Luca. Lo abandonaron frente a la casa de mi novio y le habian ajustado el collar para ahorcarlo, tenia muy lastimada la zona del cuello. Super bueno, educado e inteligente para recibir ordenes. Sabe sentarse, espera orden para comer y se lleva bien con otros animales. Le cuesta la soledad por el abandono y si se lo deja solo tiende a romper lo que tenga cerca, necesita paseos o algun juguete para liberar esa ansiedad. Castrado, Desparasitado, vacunado.','@yamigambera',15);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Zafira',1,'Anios',2,'https://i.postimg.cc/KzsPBMyj/24.jpg','Se lleva con perros, gatos y ninios. Es muy cariniosa. Castrada, desparasitada','@joogiros',16);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Alma',7,'Anios',2,'https://i.postimg.cc/x8JKR10R/25.jpg','Alma es una gata blanca con manchas negras, tiene un ojo de cada color y es muy territorial. Me gustaria encontrar un lugar especial con algo de naturaleza para que ella pueda disfrutar de un arbol, pasto, etc y no tener que vivir encerrada en un departamento.','@migataalma',16);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Lorenzo',3,'Meses',1,'https://i.postimg.cc/q7JyFLJg/26.jpg','Desparasitado y con pipeta al dia. Es super amoroso, mimoso y ronronero. Se lleva bien con otros gatitos y perros. Sabe usar sus piedritas. Si bien esta completamente sano, tiene un parpado que se dobla hacia adentro, esto no representa ninguna enfermedad ni problemas en su vision, y se resuelve con una cirugia. Su veterinario recomienda operar su parpado en simultaneo con su castracion, por lo que hay que esperar, pero no queremos que el pierda la oportunidad de tener una familia.','@hociquitos.ok',15);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Lolita',2,'Anios',2,'https://i.postimg.cc/WbZGqzYp/27.jpg','Loli es un amor, te recibe con muchos besos y pide carinio todo el tiempo. Anteriormente estuvo con unas personas que la maltrataban, pero por suerte eso es parte de su pasado. Sabe hacer sus necesidades afuera. Convive bien con otros animales. Ya esta castrada y desparasitada. La llevamos a domicilio.','@hociquitos.ok',15);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Luna',5,'Meses',2,'https://i.postimg.cc/2SFnTJfP/28.jpg','Es super mimosa y juguetona.','@verito_t',13);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Blanqui',9,'Meses',2,'https://i.postimg.cc/FHQjyvwy/29.jpg','No se lleva con gatos, y solo con perros tranquilos. Esta castrada, desparasitada y despulgada. ','@michisadopciones',17);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Nero',10,'Anios',1,'https://i.postimg.cc/mrmCWHkj/30.jpg','Es VIF y Vilef postivo. Es un amor, pero tiene olor en su boca y larga una baba marron producto del vilef. Lo castre y di antirrabica. Tengo un gato Vif y Vilef negativo, vivo en un monoambiente y no puedo tenerlo. Necesito que alguien lo transite o adopte para darle sus mejor vida. es viejito, no sabemos cuanto le quede de vida, pero esta animado, come, pide mimos, todo.','@theblingflower',18);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Africa',6,'Meses',2,'https://i.postimg.cc/XJh5p6wy/31.jpg','Aparecio en el patio de casa en busca de agua y alimento, muy mimosa y cariniosa. La estamos alimentando porque esta muy flaquita hasta encontrarle hogar, pero no podemos adoptarla porque ya tenemos otra gatita. Solo con proteccion en ventanas y balcon. Necesita ser vacunada y desparacitada ya que al ser de la calle dudamos que haya tenido algun tipo de cuidado alguna vez.','@giulianobderosa',19);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Pepe',45,'Dias',1,'https://i.postimg.cc/63TRWpGX/32.jpg','Lo estoy teniendo en mi hogar desde que nacio pero lo tengo que dar en adopcion urgentemente porque por un problema personal ya no voy a estar para poder darle la atencion y cuidado que necesita. ','@__staystrong',20);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Bless(bendicion)',8,'Meses',2,'https://i.postimg.cc/4xc7V6zx/fec97fa8-c202-4789-8e18-731331417c4b.jpg','Gatita SUPERRR AMOROSAAAAA. CARIniOSA. EDUCADISIMA. Y MAS QUE BUENA. SI BUSCAS INCLUIR A TU FAMILIA UN SER AMOROSO COMPAniERO Y MUY AGRADECIDO. CONTA CON BLESS. QUE ES LA MAS LINDA GATITA. Se franelea (le encantan los mimos)','@Camifalc',21);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Matilda',1,'Anios',2,'https://i.postimg.cc/V6vzBw3W/d93fee66-8f4e-4f5a-83ac-0a063297eb6c.jpg','Hola! Matilda es una gatita que se encuentra en un almacen. Es un poco feral, pero no es mala. Ya tuvo dos partos, y no queremos que tenga mas bebes. Sufrio mucho, le partieron la mandibula y le quedo un colmillo afuera y tiene pocos dientes. Creemos que se merece un hogar, alguien que este dispuesto a darle su tiempo hasta que se adapte a las caricias y el amor. Necesita un poco de socializacion. Se da con seguimiento y castracion obligatoria.','@hogarde.michis',21);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('El clan Primavera',50,'Dias',2,'https://i.postimg.cc/mgTkzv28/aeca905e-53b3-48ef-a39e-823a323fe24c.jpg','Hola! Se dan en adopcion a 4 gatitos, dos naranja y blanco y otros dos negros y blancos. Se desconoce el sexo se cada uno. Se pide seguimiento de por vida y castracion obligatoria cuando tengan la edad.','@hogarde.michis',21);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Reinita',1,'Anios',2,'https://i.postimg.cc/zfmdFF6t/60294d05-509f-4b3f-a8ef-3715dd391f2e.jpg','-','@roxana_carol',22);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Mama gata',3,'Anios',2,'https://i.postimg.cc/14hgj4SQ/576bfb18-cd50-4d80-9f15-6a9f37833717.jpg','-','@roxana_carol',22);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Panchita',2,'Anios',2,'https://i.postimg.cc/pXbY7Lqr/1bd2696e-8b09-49c9-9683-a668b88ea739-Ne-Ka5-Rd.jpg','Tiene entre 1 y 2 anios, pesa 15 kg, tamanio mediano. Esta castrada, con vacunas al dia y desparacitada. Es una perrita muy amorosa, mimosa y obediente. Se lleva muy bien con otros perros. Es muy guardiana, suele ser asustadiza con personas que no conoce. Buscamos una familia que le de mucho amor y la cuide, si es en companiia de otro perro mucho mejor.  Si estas interesado/a por favor comunicate con nosotros. ','@male.cala',22);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Loki',6,'Meses',1,'https://i.postimg.cc/gkmL8XgV/931a22d8-6713-44b9-902c-b8c903eeeda5.jpg','Gatito negro de aproximadamente 6 meses, amoroso y se lleva bien con otros gatos. Muy mimoso! ','@antoo.16.05',23);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Floyd',2,'Anios',1,'https://i.postimg.cc/htwGyf13/9715d7a0-b58d-4b0d-a9a8-44e66c2d3d6a.jpg','Floyd sobrevivio solito dos anios en las calles. Esta en transito en un patio con un techo pequenio. Ya fue castrado, vacunado, desparasitado, es positivo VIF y VILEF, debe convivir con gatos con los mismos virus o ser gato unico. (En el transito viven dentro de la casa 3 gatos sin esos virus, es por eso que Floyd no debe tener contacto directo con ellos, las enfermedades no son contagiosas para perros y personas) Esta sano mas alla de ser portador, tiene los dientes impecables y al ser un gato joven goza de buena salud. Es muy carinioso y dosil. Quiere estar con gente y le gusta dormir en brazos. Aprendio a usar las piedritas. Solicito adopcion o un mejor transito para que pueda estar dentro de una casa y no volver a pasar un invierno mas a la intemperie.Paso de dormir bajo los autos en la calle, a estar en un patio pero se merece tener una familia amorosa. LLora todo el dia pidiendo entrar a la casa, y estos dias con tanta lluvia y tormenta electrica lloro mucho mas. Lo llevamos al domicilio y de ser necesario nos hacemos cargo de los gastos de comida y piedritas. Unico requerimiento que no pueda salir a la calle o a terrazas vecinas.','@claupaladea',23);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Pana',3,'Anios',2,'https://i.postimg.cc/fyLnQvw7/140c6580-6260-4165-8ca3-e8dbef957827.jpg','Encontre a esta gatita y le pusimos pana pq hace muchos pancitos de panadera, es una gata excelente, se lleva bien con otros gatos y es muy mimosa. Quiero conseguirle una casa donde este tranquila y segura, ya que le tiene miedo a los ruidos de la calle y se esconde abajo de la cama (pero sale si le das mortadela!) ','@diamondsforheda',24);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Tom',4,'Anios',1,'https://i.postimg.cc/ZKGgwmyx/75b9665f-e96c-4654-bf84-48999a6a93bc.jpg','Tom es un gatito super companiero y charlatan. Es perfecto para alguien que busque un gatito que este 24/7 dando amor y esperando recibirlo. No es gato estereotipo en ese sentido ya que lo que mas disfruta es la companiia y los cariniitos','@didivit',24);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Invitado',1,'Anios',1,'https://i.postimg.cc/fTnpKZdj/6e84549d-ecce-43ba-83bd-8bc9b3b9b902.jpg','Encontre a Invitado tirado en la puerta de una casa abandonada muy flaco y con una pata rota. Luego de cuidarlo por un tiempo su pata ya sano y esta subiendo de peso. Lamentablemente salio positivo en VIF por lo tanto el solo puede convivir con otros gatos tambien positivos o con otros animales (perros, aves, etc). El VIF no afecta su calidad de vida ni a humanos. El es super amoroso y companiero, le encantan los mimos y estar atras de uno. Por su pata y su bajo peso el no es capaz de saltar muy alto pero eso no le molesta en lo absoluto. Ya esta vacunado y desparasitado, solo faltaria castrarlo. ','@_pia.caro_',24);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Sally',3,'Anios',2,'https://i.postimg.cc/SQ8tj5PX/a25f7f95-3ecf-4e7a-a03a-ce417d01207b-cu2-GOLE.jpg','Chiquita y deshinibida, ella puede ser el alma de tu casa, es muy sociable y le apasiona pedir mimos y caricias. Si queres una companiera amorosa ella es la mejor opcion!!! Esta castrada y lista para encontrar su familia ideal!! Ayudanos a sacarla de las calles!!!','@ceroprofesion',24);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Tony',7,'Anios',1,'https://i.postimg.cc/x1FP6y7D/686c463c-ca62-4e52-8466-71026305faae-ni-Utt73.jpg','Tony esta buscando una familia que le brinde mucho amor toda su vida!
- macho 
- 7 anios aprox.
- castrado
- vacunado contra la antirrabica y la sextuple
- desparacitado
- despulgado
- debe ser hijo unico
Es super mimoso y jugueton! Se merece un hogar donde lo mimen y lo llenen de amor.Historia: Tony fue rescatado de un mercado chino donde estaba pidiendo comida muerto de hambre y solo recibia insultos, empujones y amenazas, decian que si nadie se lo llevaba lo iban a llevar para el fondo donde hay una carniceria. La cuestion es que mas alla de mi situacion economica y falta de espacio para tomar otro caso, decidi hacerlo. Que mas podia hacer?  En los siguientes dias no consegui transito asi que decidi transitarlo yo. Estaba desnutrido, sucio, triste. El primer dia vomito bolsas de plastico, cada vez que lo sacaba a pasear queria romper una, pensando que no iba a tener para comer. Al pasar de los dias se dio cuenta que nunca mas ibamos a permitir que le faltara comida y perdio esos habitos. Ahora solo queda conseguir una familia que lo ame hasta que sus ojitos se cierren y trascienda este plano. Si queres sumar a Tiger a tu familia no dudes en escribirnos, si nos ayudas a difundir tambien seria de gran ayuda! Gracias!','@feria.violettt',24);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Loli',7,'Meses',2,'https://i.postimg.cc/7h66t7dd/929b32d0-82ed-445e-80f9-db4ca9dc8401.jpg','Ella es Lolita.Energetica, juguetona y un poco miedosa pero cuando toma confianza es una pegote! 
Castrada, desparacitada y vacunada contra rabia. 
Vino desde Laferrere, deambulaba por las calles y sospechamos que la corrian de los lugares, por eso es un poco miedosa y se asusta con los ruidos fuertes. Por suerte estos meses que estuvo en el refugio mejoro mucho su confianza y descubrimos que es una juguetona de primera
Ideal para una familia con integrantes tranquilos.
Se lleva perfecto con otros perros y especies! 
Hacemos un seguimiento para ver como evoluciona su adopcion','@patitasenlucha',27);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Charly',9,'Meses',1,'https://i.postimg.cc/bNn8y3xL/13189431-ecbc-486a-a6be-ac4cb9011a00.jpg','Charly es un machito tranquilo, dulce y carinioso! Ideal para una familia con chicos. El esta castrado y vacunado contra rabia! Llego a nosotras porque nos avisaron que habia un perrito deambulando y comiendo basura en un basural de Laferrere
La historia de Charly desde tan chiquito no empezo feliz pero sabemos que ahora puede conseguir una familia que pueda ortogarle seguridad, amor y por supuesto mucha comida para que disfrute! Si le das una oportunidad a Charly el te lo va a agradecer eternamente con su dulzura','@patitasenlucha',27);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Negrito',1,'Anios',1,'https://i.postimg.cc/WzvRhP6n/3f7da315-7bae-44f3-915a-937294f6c398.jpg','Es muy manso y carinioso, se ha dejado trasladar sin problema, tambien se porto muy bien en el veterinario. Ya fue desparasitado y vacunado contra la rabia. Posible castracion proxima.
Se llevada bien con otros gatos, pero no con perros. Actualmente se encuentra en transito, pero se busca otro transito o adopcion.','@maimico',27);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Leila',2,'Anios',2,'https://i.postimg.cc/XYZ2Sz97/b1f1f938-508c-4e4e-a9e6-67b12b0c24c9.jpg','Gata hembra de aproximadamente 2 anios. Sospechamos que puede estar embarazada, ya que no fue castrada. Tiene un corte debajo del ojo, pero la llevamos al veterinario y le estamos dando medicamento, ademas que la inyectaron con antibioticos y antiinflamatorios. Es muy tranquila, y tambien cariniosa.','@wine_tear',14);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Bruno',4,'Meses',1,'https://i.postimg.cc/L8BJXHty/98689cd3-33c8-457f-8504-774d969e32a7.jpg','Joven gato macho de 3 a 4 meses. Muy tranquilo y mimoso, es un poco jugueton y curioso. ','@wine_tear',14);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Cokito',9,'Meses',1,'https://i.postimg.cc/cHjMdQwy/5705e474-b5dd-4904-b8b5-d5689a76af1f.jpg','Les presentamos a Cokito, todo un galan de primera! Su hobbie? Los mimos!
Ronronea solo con verte, entra en confianza sin mucho esfuerzo por lo que es ideal para una familia de varios integrantes. Se lleva bien con todo tipo de especies. Esta castrado, desparacitado y vacunado contra rabia!
Si queres y estas interesado en integrar a un nuevo miembro en la familia y que se como cokito, no dudes en llenar el formulario de Pre-Adopcion!','@patitasenlucha',25);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Khala',7,'Meses',2,'https://i.postimg.cc/htznjnHk/bb4af808-4192-4673-a052-95c2e0e8663a.jpg','Ella es Khala. Dulce, mimosa y companiera, apenas te ve y ya empieza a ronronear. Esta desparacitada, recien castrada y vacunada contra rabia
Khalita fue rescatada de los techos del barrio de Florida, la encontramos llorando arriba de una chapa sin poder bajar. Aun asi ella es super agradecida y nunca le van a faltar los mimos!
Ideal para una casa donde quieran una gatita juguetona! Recordemos que al ser bebe puede romper, rascar, morder o rasguniar sin querer! 
-Pedimos redes de proteccion tanto en balcones como en ventanas al exterior!
-Si estas interesado en adoptar a Khalita podes completar el formulario de Pre-Adopcion y nos pondremos en contacto en cuanto lo veamos. MUCHAS GRACIAS! ','@patitasenlucha',25);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Thor',6,'Anios',1,'https://i.postimg.cc/85CtppYW/708eccdf-3f5c-4889-be46-0fc4c9fe95bf.jpg','Thor es super carinioso , tranquilo le encanta jugar no muerde se lleva muy bien con los ninios , esta acostumbrado estar adentro o en un jardin','@marce',25);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Cersei',1,'Anios',2,'https://i.postimg.cc/858M31SN/5157a571-2ab4-4bd0-b6e2-0d7059d674c0.jpg','Cersei es parte de la gran cantidad de gatos que sacamos del edificio de Constitucion. Tambien es mama de la camada de Ragnar, Rollo, Rob y Jon que por suerte estan todos adoptados. Ella al igual que las demas hembras, estaba sin castrar, flaca sin comida viviendo sobre la terraza del lugar, les tiraban las sobras y le sacaban a los bebes para que los nenes del lugar pudieran "jugar". Pero eso ya quedo todo atras, tuvo a su ultima camada donde nos encargamos que los tuviera con ella los dos meses que corresponden en un lugar calentito y con comida a disposicion. 
La castramos, vacunamos y hace unos meses que ya esta buscando familia!
Cersei al principio era muy reacia al contacto humano pero con un trabajito de mucha comida rica, caricias y hablarle despacito pudo abrirse al mundo del amor incondicional a las personas. 
Hoy tiene 1 anio aprox. Esta castrada y vacunada. Es un amor que se pone a ronronear y maullar para llamar la atencion. Puede ir con otros gatos aunque a veces es media cabrona al principio 
Hace parte de tu hogar a Cersei que no te vas a arrepentir!','@patitasenlucha',25);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Bimbo',1,'Anios',1,'https://i.postimg.cc/nh4J72h2/e54efad2-6de9-4e88-8dbe-cea8bf3b93fe.jpg','Bimbo es un cachorro de 18 meses castrado y vacunado. Es super carinioso y jugueton. Necesita una familia que le pueda dar mucho amor y que tenga espacio para correr y andar. Bimbo es lo mas bello que te puede suceder. ','@rosanabrugna',28);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Lila',4,'Meses',2,'https://i.postimg.cc/zDTZ4pnr/9d6eea62-8638-40c7-a666-cc37cf3e67f9.jpg','Lila tiene 4 meses, la encontre debajo de los autos cuando tenia 2 meses. Esta vacunada y desparacitada. La tengo en transito porq iban a adoprarla y la dejaron a la espera. Ya no puedo tenerla mas, busca alguien que le de mucho amor. Es muy cariniosa y juguetona','@florenciavega1.ok',29);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Milo',7,'Meses',1,'https://i.postimg.cc/zD7pLgNh/1d023cc8-83d8-4b2e-91c0-5dd0dcd78ce5.jpg','Milo es un gato de 7 mese, vacunado y desparacitado. Lo tengo en transito, pero ya no puedo tenerlo mas, es super mimoso, le encanta estar a upa y que le den mucho amor. Se necesita adopcion urgente! ','@florenciavega1.ok',29);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Misha',6,'Anios',2,'https://i.postimg.cc/hPwYjd8r/f626f219-2e11-484d-b1a4-df1a9c087591.jpg','Es una hermosa gata adulta. Tiene todas las vacunas esenciales. Esta desparasitada. Estuvo enferma a principio de anio, higado graso, pero ahora esta muy sana y fuerte. Esta castrada. Pesa 7kg (aprox, hace 5 meses no es pesada). Es bastante independiente pero cuando esta tranquila le gusta jugar y recibir mucho carinio. No puedo tenerla mas porque me voy a mudar a un dpt mas pequenio y creo que ella se merece algo mejor que eso, la adoro muchisimo, es toda mi vida asi que busco a alguien que la pueda amar tanto como yo y le de la vida que ella necesita y la haga feliz.','@nazarena_alessia',30);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Michael',1,'Anios',1,'https://i.postimg.cc/284HzK6z/2fa63549-a14e-4ae8-9387-5f4625d4d397.jpg','Michael es un gatito super curioso y jugueton.
Esta castrado, vacunado y desparasitado. Es muy mimoso y disfruta mucho la companiia ','@rpometti',31);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Cloe',1,'Anios',2,'https://i.postimg.cc/MTmTZwh7/312753668-514233756919332-4706537825479529954-n-Xgaze6-H.jpg','Es hembra. Tiene 1 anio y medio ya esta castrada, desparasitada y vacunada. Es re buena. Buscamos un HOGAR donde la amen como ella se merece. Fue adoptada anteriormente y a la semana la devolvieron en malas condiciones. Me partio el alma, ya sufrio mucho. Si pueden adoptarla nos ayudarian mucho! Desde ya muchas gracias.','@pa_tricia202',32);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Odin',6,'Meses',1,'https://i.postimg.cc/wv2mfDTY/c46d2e65-38bc-45fc-b60e-acdab6a0e30d-db5-CE95.jpg','Hola! me llamo odin, soy macho y tengo 6 meses.
Soy re carinioso, jugueton y companiero. Me encanta dormir, si es por mi dormiria todo el dia!! Mi mami no me puede tener mas por falta de espacio y me esta buscando un hogar donde me den todo el amor y atencion que merezco.','@paloo.ledesma',33);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Flora y Pantera',55,'Dias',2,'https://i.postimg.cc/ZK8CVrf7/1b7ff300-4b68-47b1-b192-d8bb2fac06d4.jpg','FLORA Y PANTERA ESTaN BUSCANDO HOGAR PARA SIEMPRE 
Ellas dos llegaron con muchos parasitos, flaquitas y con pulguitas pero no mucho mas! Con mucho carinio, paciencia y comidita rica se pusieron bien gorditas y su humor cambio (signo de que se sentian mejor). Aprendieron a convivir con otros y  en cuestion de horas (por no decir minutos)
Ahora Flora y Pantera estan buscando su familia ideal por siempreee
PRIORIZO ADOPCIONES CONJUNTAS o en su defecto hogares en los que haya haya una mascota. Es un mito lo de que dos gatos dan mas trabajo que uno! Se entretienen solos a todas horas
Son el duo perfecto
Saben usar las piedritas, se entregan desparasitados y despulgados!!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Luna',45,'Dias',2,'https://i.postimg.cc/vmzrjJ3K/f2e3f821-8c1b-485c-bf52-6b33e33d15db.jpg','Luna tiene 45 dias de vida y junto a sus dos hermanitos (Vaqui y Simon) fueron rescatados y ellos eran muuy bebes. Estuve con mamadera y jeringuitas para que se alimenten con leche deslactosada, de ahi pase a leche con pate de bebes y una vez que les crecieron del todo los dientitos incorporaron alimento solido. Ahora ya estan 10 puntos, des parasitos y despulgados, comiendo alimento solido y disfrutando la vida!!Son los tres super mimosos, juguetones y ronroneros, si estan solitos duermen los 3 acurrucados y sino, duermen pegaditos al humano, son suuuper suaves y divertidos. ','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Vaqui',45,'Dias',1,'https://i.postimg.cc/VLQFJWrD/06d5c96d-ee8d-411e-b4fa-578e49e942fe.jpg','Vaqui tiene 45 dias de vida y junto a sus dos hermanitos (Simon y Luna) fueron rescatados y ellos eran muuy bebes. Estuve con mamadera y jeringuitas para que se alimenten con leche deslactosada, de ahi pase a leche con pate de bebes y una vez que les crecieron del todo los dientitos incorporaron alimento solido. Ahora ya estan 10 puntos, des parasitos y despulgados, comiendo alimento solido y disfrutando la vida!! Son los tres super mimosos, juguetones y ronroneros, si estan solitos duermen los 3 acurrucados y sino, duermen pegaditos al humano, son suuuper suaves y divertidos Si estas interesad@ en adoptar a alguno de ellos (o a dos o a los tres) no dudes en escribirme o completar el formulario de Pre-Adopcion. (Vaqui tiene la nariz colorada en las fotos porque tuvo honguitos y porque de bebe metia toda la trompa en la comida y se quedo peladito, ya esta 10/10!)
Priorizo adopciones conjuntas o que en el hogar ya haya algun otro gato! Compromismo de castracion SI o SI, redes de proteccion SI o SI, vacunacion SI o SI, alimentacion de calidad SI o SI. Dejo mi Instagram: @rescataditos.lomas','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Simon',45,'Dias',1,'https://i.postimg.cc/qBXNGsDm/0b312dfa-a10b-4263-8f26-75de6f2cc157.jpg','Simon tiene 45 dias de vida y junto a sus dos hermanitos (Vaqui y Luna) fueron rescatados y ellos eran muuy bebes. Estuve con mamadera y jeringuitas para que se alimenten con leche deslactosada, de ahi pase a leche con pate de bebes y una vez que les crecieron del todo los dientitos incorporaron alimento solido. Ahora ya estan 10 puntos, des parasitos y despulgados, comiendo alimento solido y disfrutando la vida!! Son los tres super mimosos, juguetones y ronroneros, si estan solitos duermen los 3 acurrucados y sino, duermen pegaditos al humano, son suuuper suaves y divertidos. ','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Blair',55,'Dias',2,'https://i.postimg.cc/NMtgyVtQ/dcc20728-4e9e-49eb-b6e1-11eba13888ed.jpg','A Blair la abandonaron junto con su hermana Serena en la calle y ellas se resguardaron en la entrada de una casa con rejas, por suerte las vi y ya estan a salvo. Estaban llenas de pulgas y mugre, las banie, desparasite y despulgue, y ya estan hermosas.Son super mimosas, Blair es la mas loca y Serena la mas pancha y tranquila, hacen el duo perfecto!!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Serena',55,'Dias',2,'https://i.postimg.cc/rF0vkj6j/1864cb73-a2e8-443e-9770-1b77dc56ef91.jpg','Blair & Serena son dos hermanitas hembras de 55 dias que habian tirado en la entrada de una casa con rejas pero sobre la vereda y corrian mucho riesgo. Las encontre llenas de pumgas y sucias, las banie, desparasite, despulgue y cuide y estoy desesperada buscandoles hogar! Si te enamoraste de una de ellas o de las dis hablame! Pueden ir en adopcion conjunta o separadas','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Tomi',55,'Dias',1,'https://i.postimg.cc/8CjyRP1H/873f09d1-e907-47be-91ab-62c025612278.jpg','TOMI tiene 55 dias aprox y fue rescatada junto a sus tres hermanitos (Branca, Carlitos y Gina) del abandono, de la indiferencia, de la calle y de la muerte segura- OMI se entrega desparasitado, despulgado y sabiendo usar las piedritas!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Gina',55,'Dias',2,'https://i.postimg.cc/TPMy9tx4/667901f7-1d3a-4872-a3f5-299e291bfca9.jpg','Gina tiene 55 dias aprox y fue rescatada junto a sus tres hermanitos (Tomi, Carlitos y Branca) del abandono, de la indiferencia, de la calle y de la muerte segura. Estos cuatro hermanitos son super companieros, mimosos y juguetones, por eso queremos que se vayan en adopcion conjunta o que haya otros gatos en el nuevo hogar!! Gina se entrega desparasitada, despulgada y sabiendo usar las piedritas!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Branca',55,'Dias',2,'https://i.postimg.cc/TPK6K6B8/abb473c0-0904-4d19-83d5-9099d9f93cc4.jpg','Branca tiene 55 dias aprox y fue rescatada junto a sus tres hermanitos (Tomi, Carlitos y Gina) del abandono, de la indiferencia, de la calle y de la muerte segura. Estos cuatro hermanitos son super companieros, mimosos y juguetones, por eso queremos que se vayan en adopcion conjunta o que haya otros gatos en el nuevo hogar!! BRANCA se entrega desparasitada, despulgada y sabiendo usar las piedritas!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Carlitos',55,'Dias',1,'https://i.postimg.cc/fR32XRWv/2a1ab133-3f7f-4366-8a95-cc41cbf64e5c.jpg','Carlitos tiene 55 dias aprox  y fue rescatado junto a sus tres hermanitos (Tomi, Branca y Gina) del abandono, de la indiferencia, de la calle y de la muerte segura. Estos cuatro hermanitos son super companieros, mimosos y juguetones, por eso quiero que se vayan en adopcion conjunta o que haya otros gatos en el nuevo hogar!! CHARLI se entrega desparasitado, despulgado y sabiendo usar las piedritas!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Moe',2,'Meses',1,'https://i.postimg.cc/tgj3TqsJ/ae17dc45-fe99-47d6-bfe6-8b91e70270d2.jpg','Moe tiene 2 meses de edad y fue rescatado junto a sus dos hermanitos (Curly y Joe). Moe fue el mas asustadizo de los tres, el que mas costo que confie en el humano pero por suerte estaba con sus hermanitos que lo ayudaban en el proceso Son un soporte entre ellos, por eso queremos que se vayan en adopcion conjunta o que haya otros gatos en el nuevo hogar!!
MOE se entrega desparasitado, despulgado y sabiendo usar las piedritas!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Joe',2,'Meses',1,'https://i.postimg.cc/PqTDHS78/585e9627-1082-439a-8086-762fa7f7e5af.jpg','Joe tiene 2 meses de edad y fue rescatado junto a sus dos hermanitos (Moe y Curly). Joe al principio se tomo su tiempo en confiar en el humano pero si bien bufaba, ni bien era acariciado,empezaba ese motorcito de ronroneo interminable Joe es sin duda el mas charleta de los tres y el que mas busca al humano, se la pasa maullando para que lo acaricien Estos tres hermanitos son super companieros y juguetones, por eso queremos que se vayan en adopcion conjunta o que haya otros gatos en el nuevo hogar!!
JOE se entrega desparasitado, despulgado y sabiendo usar las piedritas!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Curly',2,'Meses',1,'https://i.postimg.cc/mZJmQFk6/e5e0d17e-cb40-4ce0-8650-3994daffea8f.jpg','Curly tiene 2 meses de edad y fue rescatado junto a sus dos hermanitos (Moe y Joe). Curly desde el primer momento fue el mas mansito y carinioso, si bien desconfiaba, a la primer caricia ya estaba ronroneando y maullando pidiendo mas mimos Estos tres hermanitos son super companieros y juguetones, por eso queremos que se vayan en adopcion conjunta o que haya otros gatos en el nuevo hogar!!
CURLY se entrega desparasitado, despulgado y sabiendo usar las piedritas!','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Fitu',2,'Meses',1,'https://i.postimg.cc/pXPpcsm9/d214bbed-c392-46a0-a334-f0a8dc82b796.jpg','FITU fue rescatado de la calle, siempre es la misma historia y siempre me sorprende lo gentiles, agradecidos y amorosos que son los gatos a pesar de haber vivido un horror este bebe de 2 meses esta buscando su hogar definitivo, donde lo amen y llenen de mimos, es el mas jugueton y mimoso, duerme abrazaditooo!! Aprendio a comer comida solida y a usar las piedritas, es un gatito muy hermosooooo Es re jugueton y franelero, ama estar a upa durmiendo y jugando Lo ideal es que tenga un hermano gatuno o perruno!! Fitu se entrega desparasitado y despulgado!!  Si te interesaste en Fitu no dudes en completar el formulario de Pre-Adopcion de la pagina de Catpuccino o hablarme al privado! Instagram: lo.velazquezz','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Rufi',9,'Meses',1,'https://i.postimg.cc/8PsVCv3K/1e54b3a4-6f98-4728-8c78-8eb5d7e426f4.jpg','Rufi fue encontrado en la calle corriendo entre los autos, por suerte alguien que no miro para el otro lado decidio ayudarlo y rescatarlo Lo mas probable es que de no haber sido asi Rufi estaria muerto atropellado. el es el gatito mas perfecto que existe, es todo lo que esta bien, es mimoso, dulce, bueno, companiero, dormilon, ronronero, jugueton con el humano, perros, gatos, ninios, y hasta solo pasa horas y horas jugando solito Rufi se entrega castrado, desparasitado y despulgado!!! Si te interesaste en el gordo completa el formulario de Pre-adopcion de la pagina de Catpuccino o hablame al privado! Instagram: @lo.velazquezz','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Draco',45,'Dias',1,'https://i.postimg.cc/tRZKQbVw/2056ac76-f156-4444-be2e-cfbf258ff3d5.jpg','DRACO llego a mi junto con su hermanito KIKO y su mama. Una madrugada volviendo para mi casa me cruce con una gata preniada y me la traje, termino teniendo cria en casa (por suerte) y tuvo a estos dos bebes hermosos Por suerte me la cruce, porque sino hubiera parido sola en la calle y a sus bebes los hubiera matado el frio que estuvo haciendo, la indiferencia y el maltrato KIKO y DRACO son dos varoncitos super pegotes entre ellos y con el humano, los mas companieros y ronroneros, se pueden ir en adopcion conjunta o seperados! 
SOLO se dan en adopcion a hogares con redes de proteccion o mosquiteros fijos. Cualquier cosa me escriben por Instagram: @lo.velazquezz','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Katia',1,'Anios',2,'https://i.postimg.cc/x82y4Lm0/b9956d49-5ddd-4e4a-83e5-b5e1a0067a31.jpg','Muy cariniosa, juguetona, le falta un ojo, nose porque razon pero parece estar operada de eso. Blanca con manchas grises.','@erikadossanto.s',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Kiko',45,'Dias',1,'https://i.postimg.cc/C1HfdXZg/01d3b1e3-715d-4350-8242-f25f674d2874.jpg','Kiko llego a mi junto con su hermanito Draco y su mama. Una madrugada volviendo para mi casa me cruce con una gata preniada y me la traje, termino teniendo cria en casa (por suerte) y tuvo a estos dos bebes hermosos. Por suerte me la cruce, porque sino hubiera parido sola en la calle y a sus bebes los hubiera matado el frio que estuvo haciendo, la indiferencia y el maltrato. KIKO y DRACO son dos varoncitos super pegotes entre ellos y con el humano, los mas companieros y ronroneros, se pueden ir en adopcion conjunta o seperados! 
SOLO se dan en adopcion a hogares con redes de proteccion o mosquiteros fijos. Cualquier cosa me escriben por Instagram: @lo.velazquezz','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Juan Carlos',9,'Meses',1,'https://i.postimg.cc/59D6bfKC/254c0b67-16df-4226-b44b-cd8526203a18.jpg','Juan Carlo aparecio en la calle a punto de partir, con una obstruccion urinaria importante... por suerte se llego a tiempo y Juan ya esta casi al 100% recuperado.Juan es el gato mas mimoso y bueno del universo, conversador y companiero, sobre todo amante de las siestas acompaniado se nota que en algun momento tuvo "familia" por lo edudado y bueno que es y que cuando dejo de ser un bebe lo descartaron como basura.','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Chiqui',7,'Meses',1,'https://i.postimg.cc/nLXyFfPX/213993fc-17d3-4f15-8c8e-09d38ea577d0.jpg','Chiqui es un gatito de una colonia que nacio en la calle, en la actualidad sigue viviendo ahi en una estacion de colectivos y trenes por falta de transitos y adopciones es tristisimo dado que Chiqui es el gatito mas bueno y sociable del mundo, supo querer a las personas estando en la calle! Cada vez que voy a verlo viene a saludarme, charlamos un rato y le dejo comidita y agua. Chiqui busca desesperadamente una familia hace mas  de 2anios, ojala este sea su momento de vivir la vida que siempre merecio. ','@lo.velasquezz',34);
INSERT INTO "Animal"("Nombre","Edad","tipoEdad","sexoID","Foto","Descripcion","Contacto","barrioID") VALUES ('Tae',2,'Anios',2,'https://i.postimg.cc/QtsJ6p1j/b21f8dc1-8f72-493a-9560-771feb19adbf-a0-Gw-B4b.jpg','Ella es Tae, es una gatita super amorosa, le gustan mucho los mimos, le agrada la gente, puede estar con perros, ella fue criada con uno, le gusta mucho jugar, esta bien criada, come balanceado y usa las piedritas sanitarias correctamente, es muy tranquila, le gusta dormir, necesita una nueva familia que la pueda llenar de amor y cuidarla!!!','@vicky_luque31',34);
