INSERT INTO "Barrio"("Nombre") VALUES ('Merlo');
INSERT INTO "Barrio"("Nombre") VALUES ('Moron');
INSERT INTO "Barrio"("Nombre") VALUES ('Munro');
INSERT INTO "Barrio"("Nombre") VALUES ('Palermo');
INSERT INTO "Barrio"("Nombre") VALUES ('Saenz Peña, Tres de Febrero');
INSERT INTO "Barrio"("Nombre") VALUES ('San Fernando');
INSERT INTO "Barrio"("Nombre") VALUES ('San Isidro');
INSERT INTO "Barrio"("Nombre") VALUES ('Temperley');
INSERT INTO "Barrio"("Nombre") VALUES ('Avellaneda');
INSERT INTO "Barrio"("Nombre") VALUES ('Caballito');
INSERT INTO "Barrio"("Nombre") VALUES ('Carapachay');
INSERT INTO "Barrio"("Nombre") VALUES ('Escobar');
INSERT INTO "Barrio"("Nombre") VALUES ('Flores');
INSERT INTO "Barrio"("Nombre") VALUES ('Hurlingham');
INSERT INTO "Barrio"("Nombre") VALUES ('José León Suárez');
INSERT INTO "Barrio"("Nombre") VALUES ('Lanus');
INSERT INTO "Barrio"("Nombre") VALUES ('Pompeya');
INSERT INTO "Barrio"("Nombre") VALUES ('Zona Norte');
INSERT INTO "Barrio"("Nombre") VALUES ('Mataderos');
INSERT INTO "Barrio"("Nombre") VALUES ('Banfield');
INSERT INTO "Barrio"("Nombre") VALUES ('Tigre');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Ballester');
INSERT INTO "Barrio"("Nombre") VALUES ('Valentín Alsina');
INSERT INTO "Barrio"("Nombre") VALUES ('Vicente Lopez');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Ortuzar');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Tesei');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Urquiza');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa de mayo');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa del parque');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Dominico');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Lugano');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Luro');
INSERT INTO "Barrio"("Nombre") VALUES ('Villa Luzuriaga');
INSERT INTO "Barrio"("Nombre") VALUES ('Zona Sur');